[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='forest_night'
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#branch#enabled = 0
  let g:airline#extensions#readonly#enabled = 0
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_section_c = ''
'''

[[plugins]] # 括弧補完
repo = "cohama/lexima.vim"

[[plugins]] # auto indent
repo = "Chiel92/vim-autoformat"

[[plugins]] # syntax highlight
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:python_host_prog='/usr/local/bin/python2'
  let g:python3_host_prog='/usr/local/bin/python3'
'''

[[plugins]] # 末尾spaceの可視化
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  nmap " :Buffers
  nmap ' :Files
  nmap 'a :Ag
'''

[[plugins]] # snake_case CamelCaseのmotionに対応
repo = 'chaoren/vim-wordmotion'
hook_add = '''
  let g:wordmotion_spaces = '_-.'
'''

[[plugins]]
 repo = 'autozimu/LanguageClient-neovim'
 rev ='next'
 on_ft = ['go', 'vue','ruby','sh','javascript','yaml']
 build = 'bash install.sh'
 hook_add = '''
   set hidden
   let g:LanguageClient_serverCommands = {
       \ 'ruby': ['solargraph', 'stdio'],
       \ 'vue': ['vls'],
       \ 'go': ['go-langserver','-gocodecompletion','-lint-tool','golint'],
       \ 'sh': ['bash-language-server', 'start'],
       \ 'javascript': ['node', '~/langserver/javascript-typescript-langserver/lib/language-server-stdio'],
       \ 'yaml': ['node', '~/langserver/yaml-language-server/out/server/src/server.js', '--stdio'],
       \ }
   " Or map each action separately
   nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
   nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
   nnoremap 'rn :call LanguageClient#textDocument_rename()<CR>
   nnoremap <C-t> <C-o>
 '''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_error = '⌶'
  let g:ale_sign_warning = '▻'
  highlight link ALEWarningSign Special
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
