
[[plugins]]
repo='Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_ft = ['neosnippet']
on_i = 1
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
  let g:neosnippet#snippets_directory='~/.config/nvim/snippets/'

'''

[[plugins]]
repo='sebdah/vim-delve'
hook_source='''
let g:delve_backend = "native"
'''

[[plugins]]
repo='Shougo/unite.vim'
